### ISSUE TITLE
Stuck on client_secret json key file not found.

### ISSUE THREAD

**Issue by MikeBlazer** [drkwng/google-search-console-api#1]
Hi there!
I am trying to run the main.py file, however I am stuck on the "client_secret json key file not found. Please enter your json key filename below:" prompt.

No matter what I enter in there, it keeps saying that key file isn't found.

What the problem may be?

**Comment by drkwng** [comment]
You can put the 'client_secret.json' file in the program folder or just write the correct name. Notice that the program searches data in the same folder.

**Comment by MikeBlazer** [comment]
I was already doing that.
The file is in the same folder where main.py is.
I've tried copying 'client_secret.json' file to every folder, it just doesn't find it.

![Screenshot_1](https://user-images.githubusercontent.com/104754551/166233898-198fbcb1-38a2-4314-bd33-3b2da4cc59c3.png)

**Comment by drkwng** [comment]
I'm sure you're doing something wrong. Check out the [README.md](https://github.com/drkwng/google-search-console-api/blob/main/README.md) again, please. Here is my consol
![EBQgKrMwCx](https://user-images.githubusercontent.com/89707175/166239319-cabb2ec3-9a33-461d-8b0a-b7d7f70728c0.png)
e
